[package]
name = "sixpunch"
version = "0.1.0"
authors = ["Lukas Werling <lukas.werling@gmail.com>"]

[dependencies]
rand = "0.3"
serde = "0.9"
serde_derive = "0.9"
bincode = "1.0.0-alpha5"
clap = "2.20"
